"""Added estimate_type and time_estimate fields safely

Revision ID: 934aa412784c
Revises: 3c165b9b63e9
Create Date: 2025-03-10 13:33:20.625013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934aa412784c'
down_revision = '3c165b9b63e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### Step 1: Add the column as nullable ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimate_type', sa.String(length=20), nullable=True))  # Initially NULLABLE
        batch_op.add_column(sa.Column('time_estimate', sa.Integer(), nullable=True))
        batch_op.alter_column('story_points',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.create_index(batch_op.f('ix_task_sort_order'), ['sort_order'], unique=False)

    # ### Step 2: Ensure all existing sort_order values are non-null ###
    op.execute("UPDATE task SET sort_order = COALESCE(sort_order, 0)")

    # ### Step 3: Alter the column to be NOT NULL ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('sort_order', nullable=False, server_default="0")  # Now enforce NOT NULL constraint

    # ### Step 4: Ensure estimate_type has a default value ###
    op.execute("UPDATE task SET estimate_type = 'story_points' WHERE estimate_type IS NULL")

    # ### Step 5: Alter the column to be NOT NULL ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('estimate_type', nullable=False, server_default="story_points")  # Now enforce NOT NULL constraint
        
    # Ensure existing rows have default values before enforcing constraints
    op.execute("UPDATE project SET start_date = CURRENT_TIMESTAMP, end_date = CURRENT_TIMESTAMP WHERE start_date IS NULL OR end_date IS NULL")

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('start_date', nullable=False, server_default=sa.func.now())
        batch_op.alter_column('end_date', nullable=False, server_default=sa.func.now())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_sort_order'))
        batch_op.alter_column('story_points',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('sort_order',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('time_estimate')
        batch_op.drop_column('estimate_type')
        
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
