"""Recreated initial migration

Revision ID: b7f90a8fdc83
Revises: 
Create Date: 2025-02-15 15:53:03.263186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f90a8fdc83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.Enum('Low', 'Medium', 'High', 'Critical', name='task_priority'), server_default='Medium', nullable=True))
        batch_op.drop_constraint('unique_task_name_per_parent', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_task_name_per_parent', ['name', 'parent_id'])
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
