"""Fix priority handling and completed_date logic

Revision ID: ffa424d7dc76
Revises: ae322a7c8995
Create Date: 2025-02-17 13:27:41.023047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ffa424d7dc76'
down_revision = 'ae322a7c8995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('epic_priority', postgresql.ENUM('P0', 'P1', 'P2', 'P3', 'P4', name='epic_priority'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('epic_priority')

    # ### end Alembic commands ###
